name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  precodetest:
    runs-on: ubuntu-latest
    container: golang:1.23.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          go mod tidy
          go test -test.v ./...